name: pre-commit.ci

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install go toolchain for pre-commit
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.0
          go install mvdan.cc/gofumpt@latest
          go install github.com/matryer/moq@latest
          go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.13.1

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Run pre-commit.ci
        uses: pre-commit-ci/lite-action@v1.0.2
        if: always()
        with:
          msg: |
            chore(deps): [pre-commit.ci] auto fixes\n\nFor more information, see https://pre-commit.ci
